const API = window.MATH_AGENT_API || 'http://127.0.0.1:8000';
const $ = (id) => document.getElementById(id);
const typeColor = {concept:'#2864f0', theorem:'#35a875', property:'#8b6df6', method:'#e59b42'};

function showMessage(text){ $('message').textContent=text; $('message').classList.remove('hidden'); }
function clearMessage(){ $('message').classList.add('hidden'); }
function renderConcepts(items=[]){ $('conceptCount').textContent=items.length; $('concepts').innerHTML=items.length?items.map(x=>`<div class="concept"><div><div class="concept-name">${escapeHtml(x.name)}</div><div class="concept-type">${escapeHtml(x.type||'concept')}</div></div><span class="similarity">${Math.round((x.similarity||0)*100)}%</span></div>`).join(''):'<div class="empty-state">未检索到相关知识点</div>'; }
function renderAnswer(text){ $('answer').classList.remove('empty-state'); $('answer').textContent=text||'暂无回答'; }
function escapeHtml(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

async function ask(e){e.preventDefault(); const q=$('question').value.trim(); if(!q)return; clearMessage(); $('askButton').disabled=true; $('askButton').innerHTML='正在推理…'; $('answerStatus').textContent='生成中'; try{const r=await fetch(`${API}/ai/ask`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})}); const data=await r.json(); if(!r.ok)throw new Error(data.detail||'请求失败'); renderAnswer(data.answer); renderConcepts(data.concepts); $('answerStatus').textContent='已完成'; if(data.knowledge_graph) renderGraph(data.knowledge_graph); }catch(err){showMessage(`暂时无法连接 Math Agent：${err.message}`);$('answerStatus').textContent='连接失败';}finally{$('askButton').disabled=false;$('askButton').innerHTML='开始推理 <span>→</span>';}}

async function loadGraph(){ $('graphStatus').textContent='加载中'; try{const r=await fetch(`${API}/concepts/graph`); if(!r.ok)throw Error('图谱请求失败'); renderGraph(await r.json());}catch(e){$('graphStatus').textContent='暂不可用';$('graphCanvas').innerHTML='<div class="empty-state">请先启动后端服务</div>';}}
function renderGraph(graph){const nodes=(graph.nodes||[]).slice(0,28), edges=(graph.edges||[]).slice(0,45); if(!nodes.length){$('graphCanvas').innerHTML='<div class="empty-state">知识图谱暂无数据</div>';return} const w=900,h=270, pos={}; nodes.forEach((n,i)=>{const col=i%5,row=Math.floor(i/5);pos[n.id]={x:95+col*175,y:48+row*62}}); const lines=edges.filter(e=>pos[e.source]&&pos[e.target]).map(e=>`<line x1="${pos[e.source].x}" y1="${pos[e.source].y}" x2="${pos[e.target].x}" y2="${pos[e.target].y}" stroke="#cbd6df" marker-end="url(#arrow)"/><text class="edge-label" x="${(pos[e.source].x+pos[e.target].x)/2}" y="${(pos[e.source].y+pos[e.target].y)/2-4}">${escapeHtml(e.relation)}</text>`).join(''); const circles=nodes.map(n=>`<g class="graph-node"><circle cx="${pos[n.id].x}" cy="${pos[n.id].y}" r="8" fill="${typeColor[n.type]||'#2864f0'}"/><text class="node-label" x="${pos[n.id].x+14}" y="${pos[n.id].y+4}">${escapeHtml(n.name).slice(0,14)}</text></g>`).join(''); $('graphCanvas').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="xMidYMid meet"><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="#a9b8c4"/></marker></defs>${lines}${circles}</svg>`; $('graphStatus').textContent=`${nodes.length} 个节点 · ${edges.length} 条关系`; $('legend').innerHTML='<span>概念</span><span>定理</span><span>性质 / 方法</span>';}
$('askForm').addEventListener('submit',ask); $('refreshGraph').addEventListener('click',loadGraph); loadGraph();
